### ISSUE TITLE
number of items by type of collector

### ISSUE THREAD

**Issue by karlesnine** [PrFalken/dellhw_trapper#1]
Hi
It is possible to have a counter of the **number of items by type of collector** ? For **example** the **total number of controller discovered**, or fans, or power supply. This in order to create alerts on the undiscovered element yet indispensable.

Thank
Karles

**Comment by PrFalken** [comment]
Implemented in [release 0.15](https://github.com/PrFalken/dellhw_trapper/releases/tag/0.15)
